FROM python:3.10

RUN apt update && apt upgrade -y

RUN curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10

COPY requirements.client.txt ./requirements.txt

RUN python3.10 -m pip install --upgrade pip
RUN python3.10 -m pip install -r requirements.txt

COPY ./*.py ./

CMD ["python3.10", "selfplay.py"]